### ISSUE TITLE
disable_off_hand_swap: true still works on worlds that are not whitelisted.

### ISSUE THREAD

**Issue by mouel466** [ItsLewizzz/DeluxeHub#66]
here is the whitelist:

```
# Disable specific worlds
disabled-worlds:
  # Should we invert the list making it a whitelist rather than a blacklist?
  invert: true
  # List your disabled worlds HERE or "worlds: []" to disable
  worlds:
    - world
```
I use multiverse and I have other worlds with different names (survival, factions, etc.) and the off_hand_swap should work fine in them, but it does not. Now I disabled disable_off_hand_swap so it would work in all of them.

Is this a bug or did I misunderstood something.
